<script setup>
import { onMounted, ref } from 'vue'; import { getApplications, getInterviews, getJobs, getMatches } from '../api'; import PageHeader from '../components/PageHeader.vue'; import { salaryRange } from '../utils/format'
const jobs=ref([]),matches=ref([]),apps=ref([]),interviews=ref([]), loading=ref(true)
onMounted(async()=>{try{const [j,m,a,i]=await Promise.all([getJobs({size:4}),getMatches(),getApplications(),getInterviews()]);jobs.value=j.records;matches.value=m;apps.value=a;interviews.value=i}finally{loading.value=false}})
const fmt=d=>d?new Date(d).toLocaleDateString('zh-CN',{month:'short',day:'numeric'}):'待更新'
</script>
<template><div><PageHeader eyebrow="OVERVIEW" title="今天，也向理想工作靠近一步" subtitle="聚合职位发现、匹配分析和求职进度，重要信息一眼掌握。"><RouterLink class="btn primary" to="/jobs">探索新职位 →</RouterLink></PageHeader>
<div class="stat-grid"><article><span class="stat-icon cyan">⌕</span><div><small>可探索职位</small><b>{{ jobs.length ? '12+' : '—' }}</b><em>持续更新</em></div></article><article><span class="stat-icon violet">◎</span><div><small>已生成匹配</small><b>{{ matches.length }}</b><em>可解释评分</em></div></article><article><span class="stat-icon amber">▤</span><div><small>求职记录</small><b>{{ apps.length }}</b><em>{{ apps.filter(a=>a.status==='INTERVIEW').length }} 个进入面试</em></div></article><article><span class="stat-icon green">◫</span><div><small>模拟面试</small><b>{{ interviews.length }}</b><em>随时练习</em></div></article></div>
<div class="dashboard-grid"><section class="panel wide"><div class="panel-title"><div><span class="eyebrow">RECOMMENDED</span><h2>近期优质机会</h2></div><RouterLink to="/jobs">查看全部 →</RouterLink></div><div class="job-rows" v-if="jobs.length"><div v-for="job in jobs" :key="job.id" class="job-row"><span class="company-logo">{{job.company.slice(0,1)}}</span><div><b>{{job.title}}</b><small>{{job.company}} · {{job.city}}</small></div><strong>{{salaryRange(job)}}</strong><RouterLink :to="`/jobs?focus=${job.id}`">查看</RouterLink></div></div><div v-else class="empty">{{loading?'正在扫描职位…':'暂无职位'}}</div></section>
<section class="panel"><div class="panel-title"><div><span class="eyebrow">PIPELINE</span><h2>求职动态</h2></div></div><div class="timeline" v-if="apps.length"><div v-for="app in apps.slice(0,5)" :key="app.id"><i></i><span><b>{{app.job.title}}</b><small>{{app.status}} · {{fmt(app.updatedAt)}}</small></span></div></div><div v-else class="empty">还没有投递记录<br><RouterLink to="/jobs">去发现合适职位</RouterLink></div></section></div></div></template>
