<script setup>
import { onMounted, reactive, ref } from 'vue'; import { addFavorite, createApplication, createInterview, getJobs, matchJob } from '../api'; import JobCard from '../components/JobCard.vue'; import NoticeBar from '../components/NoticeBar.vue'; import PageHeader from '../components/PageHeader.vue'
const filters=reactive({keyword:'',city:'',minSalary:null,page:1,size:8});const page=ref({records:[],total:0});const loading=ref(false),notice=ref('')
const flash=m=>{notice.value=m;setTimeout(()=>notice.value='',2400)}
const load=async()=>{loading.value=true;try{page.value=await getJobs(filters)}finally{loading.value=false}}
const act=async(type,job)=>{try{if(type==='favorite')await addFavorite(job.id);if(type==='apply')await createApplication({jobId:job.id,progressNote:'已从职位雷达加入求职计划'});if(type==='interview')await createInterview(job.id);if(type==='match'){const r=await matchJob(job.id);flash(`匹配完成：${r.score}分 · ${r.summary}`);return}flash({favorite:'已加入收藏',apply:'已记录投递',interview:'已生成 4 道模拟面试题'}[type])}catch(e){flash(e.message)}}
onMounted(load)
</script>
<template><div><NoticeBar :message="notice"/><PageHeader eyebrow="JOB RADAR" title="职位雷达" subtitle="按目标、城市与薪资扫描岗位，让选择建立在数据之上。"><span class="result-count">扫描到 <b>{{page.total}}</b> 个机会</span></PageHeader><form class="filter-bar" @submit.prevent="filters.page=1;load()"><label class="search-input">⌕<input v-model="filters.keyword" placeholder="搜索职位或公司" /></label><select v-model="filters.city"><option value="">全部城市</option><option>北京</option><option>上海</option><option>深圳</option><option>杭州</option><option>济南</option></select><select v-model="filters.minSalary"><option :value="null">不限薪资</option><option :value="10000">10K 以上</option><option :value="15000">15K 以上</option><option :value="20000">20K 以上</option></select><button class="btn primary">开始扫描</button></form><div v-if="loading" class="loading-grid"><i v-for="n in 4" :key="n"></i></div><div v-else class="job-grid"><JobCard v-for="job in page.records" :key="job.id" :job="job" @match="act('match',$event)" @favorite="act('favorite',$event)" @apply="act('apply',$event)" @interview="act('interview',$event)" /></div><div class="pagination" v-if="page.total>filters.size"><button :disabled="filters.page===1" @click="filters.page--;load()">上一页</button><span>{{filters.page}} / {{Math.ceil(page.total/filters.size)}}</span><button :disabled="filters.page>=Math.ceil(page.total/filters.size)" @click="filters.page++;load()">下一页</button></div></div></template>
