import request from './request'

export const login = data => request.post('/api/user/login', data)
export const getProfile = () => request.get('/api/user/profile')
export const updateProfile = data => request.put('/api/user/profile', data)
export const getJobs = params => request.get('/api/jobs', { params })
export const getJob = id => request.get(`/api/jobs/${id}`)
export const matchJob = id => request.post(`/api/matches/jobs/${id}`)
export const getMatches = () => request.get('/api/matches')
export const getFavorites = () => request.get('/api/favorites')
export const addFavorite = id => request.post(`/api/favorites/${id}`)
export const removeFavorite = id => request.delete(`/api/favorites/${id}`)
export const getApplications = () => request.get('/api/applications')
export const createApplication = data => request.post('/api/applications', data)
export const updateApplication = (id, data) => request.put(`/api/applications/${id}/status`, data)
export const getInterviews = () => request.get('/api/interviews')
export const getInterview = id => request.get(`/api/interviews/${id}`)
export const createInterview = jobId => request.post('/api/interviews', null, { params: { jobId } })
export const answerInterview = (id, data) => request.post(`/api/interviews/${id}/answers`, data)
export const getNotifications = () => request.get('/api/notifications')
export const getUnreadCount = () => request.get('/api/notifications/unread-count')
export const readNotification = id => request.put(`/api/notifications/${id}/read`)
export const readAllNotifications = () => request.put('/api/notifications/read-all')
